package tools.jackson.module.kotlin.test.github

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.RepeatedTest
import org.junit.jupiter.api.parallel.Execution
import org.junit.jupiter.api.parallel.ExecutionMode
import tools.jackson.databind.json.JsonMapper
import tools.jackson.module.kotlin.kotlinModule
import tools.jackson.module.kotlin.readValue
import kotlin.test.assertEquals

@Execution(ExecutionMode.CONCURRENT)
class GitHub1092Test {

    companion object {
        private lateinit var testJsonMapper: JsonMapper

        @JvmStatic
        @BeforeAll
        fun setup() {
            testJsonMapper = JsonMapper.builder().addModule(kotlinModule()).build()
        }
    }

    private val roomsString = """{
            "rooms": [
                {
                  "typ": "Living",
                  "animals": [
                        {
                            "typ": "Cat"
                        },
                        {
                            "typ": "Cat"
                        },
                        {
                            "typ": "Cat"
                        },
                        {
                            "typ": "Cat"
                        }
                  ]
                },
                {
                  "typ": "Sleeping",
                  "animals": [
                        {
                            "typ": "Dog"
                        },
                        {
                            "typ": "Dog"
                        },
                        {
                            "typ": "Dog"
                        },
                        {
                            "typ": "Dog"
                        }
                  ]
                }
            ]
    }
    """.trimIndent()

    val result = testJsonMapper.readValue<Result>(roomsString)

    @RepeatedTest(1000)
    fun `try serialisation and deserilization`() {
        assertEquals(result, serializeWithDeserilization(result))
    }

    private fun serializeWithDeserilization(result: Result): Result {
        val personalbetriebslageJson = testJsonMapper.writeValueAsString(result)
        return testJsonMapper.readValue<Result>(personalbetriebslageJson)
    }

}

// Data class definitions

data class Result(
    val rooms: List<Room>
)

@JsonIgnoreProperties(
    value = ["typ"], // ignore manually set typ, it will be automatically generated by Jackson during serialization
    allowSetters = true, // allows the typ to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "typ", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = LivingRoom::class, name = "Living"),
    JsonSubTypes.Type(value = SleepingRoom::class, name = "Sleeping"),

    )
/*
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "typ", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = LivingRoom::class, name = "Living"),
    JsonSubTypes.Type(value = SleepingRoom::class, name = "Sleeping"),

    )
 */
interface Room {
    @get:JsonProperty("typ")
    val typ: RoomType
}

data class LivingRoom(
    override val typ: RoomType,
    val animals: List<Cat>
) : Room

data class SleepingRoom(
    override val typ: RoomType,
    val animals: List<Dog>
) : Room

enum class RoomType {
    Living,
    Sleeping
}

@JsonIgnoreProperties(
    value = ["typ"], // ignore manually set typ, it will be automatically generated by Jackson during serialization
    allowSetters = true, // allows the typ to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "typ", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = Cat::class, name = "Cat"),
    JsonSubTypes.Type(value = Dog::class, name = "Dog"),

    )
/*
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "typ", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = Cat::class, name = "Cat"),
    JsonSubTypes.Type(value = Dog::class, name = "Dog"),

    )
 */
interface Animal {
    @get:JsonProperty("typ")
    val typ: AnimalType
}

data class Cat(
    override val typ: AnimalType,
) : Animal

data class Dog(
    override val typ: AnimalType,
) : Animal

enum class AnimalType {
    Dog,
    Cat
}
